config.unbind('m')
config.unbind('q')
config.unbind('@')
config.unbind('u')
config.unbind('d')
config.bind('d', ':scroll-page 0 0.5')
config.bind('u', ':scroll-page 0 -0.5')
config.bind('x', ':tab-close')
config.bind('X', ':undo')

config.load_autoconfig()
