# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
# hook_add = '''
# source ~/.config/nvim/plugins/vim-lsp.vim
# '''
# [[plugins]]
# repo = 'mattn/vim-lsp-settings'
# hook_add = '''
# source ~/.config/nvim/plugins/vim-lsp-settings.vim
# '''

# # 非同期
# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = '''
# source ~/.config/nvim/plugins/ale.vim
# '''


# [[plugins]]
# repo = 'preservim/nerdtree'
# hook_add = '''
# source ~/.config/nvim/plugins/nerdtree.vim
# '''
# [[plugins]]
# repo = 'Xuyuanp/nerdtree-git-plugin'

# 補完
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/asyncomplete.vim
# '''
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'
# [[plugins]]
# repo = 'prabirshrestha/async.vim'
# [[plugins]]
# repo = 'Shougo/ddc.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/ddc.vim
# '''
# [[plugins]]
# repo = 'shun/ddc-vim-lsp'
# [[plugins]]
# repo = 'vim-denops/denops.vim'
# [[plugins]]
# repo = 'Shougo/ddc-matcher_head'
# [[plugins]]
# repo = 'Shougo/ddc-around'
# [[plugins]]
# repo = 'Shougo/ddc-sorter_rank'
# [[plugins]]
# repo = 'LumaKernel/ddc-file'

# ポップアップウィンドウ
# [[plugins]]
# repo = 'Shougo/pum.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/pum.vim
# '''
