[[plugins]] # tomlファイルのシンタックス
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]] # jsonのシンタックス
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]] # JavaScriptのシンタックス
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]] # JavaScriptのprettier
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]] # pythonの自動補完プラグイン
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = ['py']
