# ヘルプの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# 選択範囲をGoogle翻訳
[[plugins]]
repo = 'skanehira/translate.vim'

# Twitter
[[plugins]]
repo = 'twitvim/twitvim'

# markdown
[[plugins]]
repo = 'skanehira/preview-markdown.vim'
hook_add = '''
source ~/.config/nvim/plugins/preview-markdown.rc.vim
'''

# ステータスラインの表示内容強化
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/lightline.rc.vim
# '''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.rc.vim
'''

# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'
# hook_add = '''
# source ~/.config/nvim/plugins/vim-airline.rc.vim
# '''

# ステータスラインにbranch名
[[plugins]]
repo = 'tpope/vim-fugitive'

# インデントの可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 末尾の全角半角空白文字を赤くハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# ノーマルモードでコメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

# インデントの深さを可視化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# カラースキーマ
# iceberg
# [[plugins]]
# repo = 'cocopon/iceberg.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/iceberg.rc.vim
# '''

# gruvbox
# [[plugins]]
# repo = 'morhetz/gruvbox'
# hook_add = '''
# source ~/.config/nvim/plugins/gruvbox.rc.vim
# '''

# dracula
[[plugins]]
repo = 'dracula/vim'
hook_add = '''
source ~/.config/nvim/plugins/dracula.rc.vim
'''

# solarized
# [[plugins]]
# repo = 'altercation/vim-colors-solarized'
# hook_add = '''
# source ~/.config/nvim/plugins/solarized.rc.vim
# '''

# onedark
# [[plugins]]
# repo = 'joshdick/onedark.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/onedark.rc.vim
# '''

# [[plugins]]
# repo = 'haishanh/night-owl.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/nightowl.rc.vim
# '''

[[plugins]]
repo = 'gkeep/iceberg-dark'

# IDEのような補完
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.rc.vim
'''

# ファイラー
# [[plugins]]
# repo = 'Shougo/defx.nvim'
# depends = ['nvim-yarp', 'vim-hug-neovim-rpc', 'vim-devicons', 'defx-icons', 'defx-git', 'nerdfont.vim']
# hook_add = '''
# source ~/.config/nvim/plugins/defx.rc.vim
# '''
# [[plugins]]
# repo = 'Shougo/nvim-yarp'
# [[plugins]]
# repo = 'roxma/vim-hug-neovim-rpc'
# [[plugins]]
# repo = 'kristijanhusak/defx-icons'
# [[plugins]]
# repo = 'kristijanhusak/defx-git'
[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['fern-git-status.vim', 'fern-renderer-nerdfont.vim', 'nerdfont.vim', 'fern-preview.vim', 'fern-hijack']
hook_add = '''
  source ~/.config/nvim/plugins/fern.rc.vim
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
source ~/.config/nvim/plugins/fern-renderer-nerdfont.rc.vim
'''

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
hook_add = '''
source ~/.config/nvim/plugins/fern-preview.rc.vim
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-devicons.vim'
hook_add = '''
source ~/.config/nvim/plugins/fern-renderer-devicons.rc.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

# ブラケット自動入力
# [[plugins]]
# repo = 'jiangmiao/auto-pairs'

# [[plugins]]
# repo = 'preservim/nerdtree'
# depends = 'nerdtree-git-plugin'
# hook_add = '''
# source ~/.config/nvim/plugins/nerdtree.rc.vim
# '''

# [[plugins]]
# repo = 'Xuyuanp/nerdtree-git-plugin'

# [[plugins]]
# repo = 'ryanoasis/vim-devicons'

# ウインドウリサイズ
[[plugins]]
repo = 'simeji/winresizer'

# ファイル検索
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'easymotion/vim-easymotion'
