[[plugins]] # ヘルプの日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # TwitVim
repo = 'twitvim/twitvim'

[[plugins]] # ステータスラインの表示内容強化
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.config/nvim/plugins/lightline.rc.vim
'''
[[plugins]] # ステータスラインにbranch名
repo = 'tpope/vim-fugitive'

[[plugins]] # インデントの可視化
repo = 'Yggdroot/indentLine'

# [[plugins]] # 末尾の全角半角空白文字を赤くハイライト
# repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # ノーマルモードでコメントアウト
repo = 'tpope/vim-commentary'

[[plugins]] # インデントの深さを可視化
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # カラースキーマ
repo = 'cocopon/iceberg.vim'
hook_add = '''
  source ~/.config/nvim/plugins/iceberg.rc.vim
'''

[[plugins]] # IDEのような補完
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
  source ~/.config/nvim/plugins/coc.rc.vim
'''

# [[plugins]] # ファイラ
# repo = 'lambdalisue/fern.vim'
# hook_add = '''
#   source ~/.config/nvim/plugins/fern.rc.vim
# '''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'Shougo/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'kristijanhusak/defx-icons'
# [[plugins]] # gitのステータス
# repo = 'lambdalisue/fern-git-status.vim'

[[plugins]] # ブラケット自動入力
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

# [[plugins]]
# repo = 'lambdalisue/glyph-palette.vim'
# hook_add = '''
#   source ~/.config/nvim/plugins/glyph-palette.rc.vim
# '''

# [[plugins]]
# repo = 'lambdalisue/fern-renderer-nerdfont.vim'
# hook_add = '''
#   source ~/.config/nvim/plugins/fern-renderer-nerdfont.rc.vim
# '''

[[plugins]] # ウインドウリサイズ
repo = 'simeji/winresizer'
