# マークダウン
[[plugins]]
repo = 'preservim/vim-markdown'
on_ft = ['markdown']

# jsonのシンタックス
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

# tomlファイルのシンタックス
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# JavaScriptのシンタックス
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript', 'typescript', 'typescriptreact']
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript', 'typescript', 'typescriptreact']
[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascript', 'typescript', 'typescriptreact']

# JavaScriptのPrettier
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript', 'typescript', 'typescriptreact']
[[plugins]]
repo = 'yuezk/vim-js'
on_ft = ['javascript', 'javascript', 'typescript', 'typescriptreact']

# コードフォーマッター
[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install --frozen-lockfile --omit=dev'
on_ft = ['javascript', 'typescript', 'javascriptreact', 'typescriptreact', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'svelte', 'yaml', 'html']
hook_add = '''
source ~/.config/nvim/plugins/vim-prettier.vim
'''

# TypeScriptのシンタックス
# [[plugins]]
# repo = 'HerringtonDarkholme/yats.vim'
# on_ft = ['javascript', 'javascriptreact', 'typescript', 'typescriptreact']
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['javascript', 'javascriptreact', 'typescript', 'typescriptreact']

# jsxのシンタックス
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['javascript', 'javascriptreact', 'typescript', 'typescriptreact']

# HTML/CSSの入力補助
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']
hook_add = '''
source ~/.config/nvim/plugins/emmet-vim.vim
'''
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

# html ライブ編集
[[plugins]]
repo = 'turbio/bracey.vim'
on_ft = ['html']

# csv
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ['csv']

# PHP
[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'
on_ft = ['php']
hook_add = '''
source ~/.config/nvim/plugins/vim-php-cs-fixer.vim
'''
