# 8bit文字を有効にする
setopt print_eight_bit
# cdした際のディレクトリをディレクトリスタックへ自動追加
setopt auto_pushd
# ディレクトリ名のみで移動する
setopt auto_cd
# 履歴を複数の端末で共有
setopt share_history
# 直前と同じコマンドラインはヒストリに追加しない
setopt hist_ignore_dups
# 重複したコマンドをヒストリに追加しない
setopt hist_ignore_all_dups
# コマンドラインの先頭に空白があれば履歴に残さない
setopt hist_ignore_space
# 余分な空白は詰めて履歴に残る
setopt hist_reduce_blanks
# コマンドのスペルチェックする
setopt correct
# コマンドラインのすべてのスペルチェックする
setopt correct_all
# ディレクトリスタックへの追加の際に重複させない
setopt pushd_ignore_dups
# フローコントロールを無効にする
setopt no_flow_control
# bgプロセスの状態変化を即時に知らせる
setopt notify
# ワイルドカード展開を使用する
setopt extendedglob
# ワイルドカードをコマンドとして使用する
setopt nomatch
# '?' '&' などをエスケープ無しで使用する
setopt nonomatch
